# Generated by Django 3.2.12 on 2022-03-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='displaytemplate',
            name='display',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
