# Generated by Django 3.2.12 on 2022-03-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0002_displaytemplate_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('display', models.JSONField()),
            ],
        ),
        migrations.RenameModel(
            old_name='DisplayTemplate',
            new_name='OverviewTemplate',
        ),
    ]
