# Generated by Django 3.2.12 on 2022-03-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0003_auto_20220321_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='overviewtemplate',
            name='description',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemtemplate',
            name='description',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
