#!/usr/bin/env bash
#
# source env/bin/activate
cd dqm
python3 manage.py makemigrations
python3 manage.py migrate
python3 manage.py shell < configdb.py # Add a superuser if needed
python3 manage.py collectstatic -i "*.py" -i "*.pyc" --noinput --link
#
# Run debug server. Use the nostatic flag to enable the use of whitenose rather than the standard Django debug handling
#
# ./manage.py runserver --nostatic
